#!/usr/bin/env bash

if [ "$#" -eq 0 ]; then
    echo "ERROR: No input CSV file provided"
    exit 1
fi

input="$1"

if [ ! -f "./$input" ]; then
    echo "ERROR: Input file not found in the current directory"
    exit 1
fi

if [[ "$input" != *.csv ]]; then
    echo "ERROR: Input file expected in a CSV format"
    exit 1
fi

if [ ! -s "./$input" ]; then
    echo "ERROR: Empty file provided"
    exit 1
fi

header_fields=$(awk -F',' 'NR == 1 { print NF; exit }' "./$input")

if [ "$header_fields" -ne 7 ]; then
    echo "ERROR: Expected 7 columns in the input"
    exit 1
fi

awk -F',' -v expected_fields="$header_fields" '
BEGIN {
    OFS = ","    # separate output columns with a comma
}

NR == 1 {
    print $1, $2, $3, $4, $5, $6    # ignoring the 7th column ($7)
    next    # move to the next row
}

{
    sub(/\r$/, "")    # remove Windows-style carriage returns (\r) from the end of a line

    if (NF != expected_fields) next    # skip if this row does not have 7 columns

    for (i = 1; i <= NF; i++) {    # check every column in the row
        if ($i == "") next    # skip if any entry is empty
    }

    if (seen[$0]++) next    # skip duplicate rows

    if ($1 == "") next    # skip a row that has no video_id

    if ($4 == 0 || $5 == 0) next    # skip if likes or dislikes are 0

    split($2, date_time_parts, "T")    # split the datetime based on the 'T'
    $2 = date_time_parts[1]    # select the first half (the half that contains the date)

    print $1, $2, $3, $4, $5, $6    # print cleaned row
}
' "./$input" > trending_videos_clean.csv